### ISSUE TITLE
Spina no longer uses wysihtml5

### ISSUE THREAD

**Issue by dankmitchell** [COSMOSMagazine/spina_summernote#3]
I think this file needs updating - `app/views/spina/admin/shared/photos/wysihtml5_insert.js.erb` to `app/views/spina/admin/shared/photos/insert_photo.js.erb`

and `wysihtml5_select_admin_photos_path` needs changing

**Comment by DanBrooker** [comment]
Looks like it might actually need to be `trix_insert.js.erb`
